### ISSUE TITLE
I18N Implement

### ISSUE THREAD

**Issue by alexclassroom** [idehweb/login-with-phone-number#3]
This repository may be behind the WordPress SVN, so I think I cannot submit the PR based on 1.4.0.

The modified codes can implement I18N, I list them as the following:
login-with-phonenumber.php, line 73
`<h3><?php esc_html_e('Personal Information', $this->textdomain); ?></h3>`

login-with-phonenumber.php, line 1457 to 1468 (including commented codes)
```
//            ["value" => "twilio", "label" => __('Twilio (International)', $this->textdomain)],
//            ["value" => "zenziva", "label" => __('Zenziva (Indonesia)', $this->textdomain)],
//            ["value" => "infobip", "label" => __('Infobip (Portugal , Brazil ...)', $this->textdomain)],
            ["value" => "firebase", "label" => __('Firebase (Google)', $this->textdomain)],
            ["value" => "custom", "label" => __('Custom (Config Your Gateway)', $this->textdomain)],
//            ["value" => "raygansms", "label" => __('Raygansms.com (Iran)', $this->textdomain)],
//            ["value" => "smsbharti", "label" => __('smsbharti.com (India)', $this->textdomain)],
//            ["value" => "mshastra", "label" => __('mshastra.com (Saudi Arabia)', $this->textdomain)],
//            ["value" => "taqnyat", "label" => __('taqnyat.sa (Saudi Arabia)', $this->textdomain)]
        ];
//        ["value"=>"custom","label"=> __('custom gateway setting', $this->textdomain)]
//        ["value"=>"saudibulksms","label"=> __('Saudi Bulk SMS (STC) (saudi arabia)', $this->textdomain)],
```
login-with-phonenumber.php, line 1854
`if (!isset($options['idehweb_term_and_conditions_text'])) $options['idehweb_term_and_conditions_text'] = __('By submitting, you agree to the <a href="#">Terms and Privacy Policy</a>', $this->textdomain);`

login-with-phonenumber.php, line 2052 and 2064
`if (!isset($options['idehweb_default_username'])) $options['idehweb_default_username'] = __( 'user', $this->textdomain);`

login-with-phonenumber.php, line 2364
`<?php echo esc_attr_x('Login with phone number', 'Button Label', $this->textdomain); ?>`

**Comment by hamidalinia** [comment]
thank you, I have solved the issues, updated to WordPress, I mentioned you name and I am happy for your help
