### ISSUE TITLE
Last week suddenly started "enter code wrong" - firebase gateway

### ISSUE THREAD

**Issue by iosc** [idehweb/login-with-phone-number#5]
hi,

I have been using your plugin for wordpress for user to register / login for more than 3 months. Everything went good until last week when few users said the login via otp no more working, either it keep loading with no result, or it did sent otp via firebase but the otp and generated code at backend user dashboard not correct

for example, put in phone number, firebase sent 6 digits number to that mobile phone, but after key it the 6 digit numbers, the error code said "enter code wrong"

i am trying the version 1.5.5, 1.5.6 and latest 1.5.7 all have the same issue

i try to debug your code, the $activation_code and $secod always not equal

Please help!

Thank you

Boyd

**Comment by hamidalinia** [comment]
Hello, thank you for using our plugin and sending issue. We are working on it. It will be ready soon.

**Comment by iosc** [comment]
hi idehweb,

Thank you for the quick response! The 1.5.9 fixed the issue ;)

I will keep using it and report any issues if found (^_^)

Cheers, Boyd
